### ISSUE TITLE
Exponent Confusion, and a questions

### ISSUE THREAD

**Issue by imukai** [MikeMcl/decimal.js-light#1]
Playing with decimal.js-light for the first time.  Ran into something and have a questions after.

1. Confusion:

dec = new Decimal(1.99).pow(199);

**dec.toExponential()** seems correct at "2.9632084641717921185e+59"

but:  **dec.e** = 8

I was expecting it would be 59.  Any idea why I'm getting 8?

2. Question:

Is there a way to format a decimal constrained to the nearest exponent of 3?  

examples:  
12345 = 12.345e+3 instead of 1.2345 e+4
123456 = 123.456 e+3 instead of 1.23456e+5

I'm ultimately wanting to convert rather large numbers into a metric-type lettering system where every 3 places is represented by a letter (ex 1.23k)

**Comment by MikeMcl** [comment]
1.
Oh, good point. Unlike decimal.js which stores the base 10 exponent in the `e` property, this library instead stores the base 1e7 exponent. I need to document this and perhaps provide an `exponent` method to get the base 10 exponent.

2.
No, not without hacking on ther library itself.

**Comment by imukai** [comment]
Ah, that explains my confusion.  I'll add that in.  Thanks for the quick response.  

No worries on #2, I can pass it through something I hacked together for another big number library (that couldn't handle decimals).  That learning process taught me a new term.. Bijective Hexavigesimal.

Anyway, thanks again.  I'll leave this open if you want to use it as a reminder to add base 10 exponent into the light library.

**Comment by MikeMcl** [comment]
Added an `exponent` method in v2.1.0.
