### ISSUE TITLE
Addition is sometimes not associative

### ISSUE THREAD

**Issue by tom-sherman** [MikeMcl/decimal.js-light#13]
```javascript

const a = new Decimal('-13.77');
const b = new Decimal('1.5612555115940468637');
const c = new Decimal('5');

const result1 = a.add(b).add(c);
const result2 = a.add(b.add(c));

console.log(result1.toString()); // "-7.208744488405953136"
console.log(result2.toString()); // "-7.2087444884059531363"
```

Fiddle: https://jsfiddle.net/es9pun76/1/

I'm not sure what is special about these values or order of addition, but the values are different when they definitely shouldn't be! `result2` is the mathematically correct result, if you were wondering 😆

**Comment by tom-sherman** [comment]
This is also a bug with decimal.js, raised it there: https://github.com/MikeMcl/decimal.js/issues/157

**Comment by MikeMcl** [comment]
There is no bug here, see [here](https://github.com/MikeMcl/decimal.js/issues/157).
