### ISSUE TITLE
Failed to run in SES

### ISSUE THREAD

**Issue by Jack-Works** [MikeMcl/decimal.js-light#20]
![image](https://user-images.githubusercontent.com/5390719/156310660-d7c712ea-8f80-48ce-97a6-1647fbc76726.png)

https://github.com/MikeMcl/decimal.js-light/blob/master/decimal.js#L1862

Change this line to

```js
Object.defineProperty(this, 'constructor', {
    value: Decimal
})
```

can fix the problem, but this looks like a compiled file, I don't know how to make a PR

**Comment by MikeMcl** [comment]
What is SES? And please describe the problem rather than expecting me to work it out from a screenshot.

In JavaScript, `constructor` is not a read-only property of an object, and this is an ECMAScript 3 compatible library, so `Object.defineProperty` is unacceptable anyway.

What is SES?

**Comment by MikeMcl** [comment]
What is SES? And please describe the problem rather than expecting me to work it out from a screenshot.

In JavaScript, constructor is *not* a read-only property of an object, and this is an ECMAScript 3 compatible library, so `Object.defineProperty` is unacceptable anyway.

**Comment by MikeMcl** [comment]
What is SES?

In JavaScript, `constructor` is *not* a read-only property of an object, and this is an ECMAScript 3 compatible library, so `Object.defineProperty` is unacceptable anyway.

**Comment by Jack-Works** [comment]
Hi! SES is a [secured EcmaScript environment](https://github.com/tc39/proposal-ses) (and it's [polyfill](https://github.com/endojs/endo/tree/master/packages/ses)), in that environment, every built-in object (including `Function.prototype`) is frozen to protect from the prototype pollution attack.

When `Function.prototype` is not frozen, set on Decimal.constructor will not change the `Function.prototype.constructor`, but create a defined property:

![image](https://user-images.githubusercontent.com/5390719/156472433-fc43d324-0fd4-4631-84d8-fcf96600ca08.png)

But very unluck, when the prototype is frozen, write the property without Object.defineProperty will throw an error:

![image](https://user-images.githubusercontent.com/5390719/156472518-97b04eb3-9c92-4bb6-b2d7-d837888abf6d.png)

> and this is an ECMAScript 3 compatible library, so Object.defineProperty is unacceptable anyway.

Is it possible to do this?

```js
if (Object.defineProperty) Object.defineProperty(this, 'constructor', { value: Decimal })
else this.constructor = Decimal
```

**Comment by MikeMcl** [comment]
Is this the only change required to make this library SES-compatible?

Anyway, this is a very hot code path and adding another `if` statement and then calling `Object.defineProperty` will be much slower then the existing simple assignment.

SES and similar efforts look interesting but they seem too marginal at the moment for me to start making changes to support them.

**Comment by Jack-Works** [comment]
> Is this the only change required to make this library SES-compatible?

Maybe not, it is just the first error that appears, maybe some other assignments need to be changed too.

> SES and similar efforts look interesting but they seem too marginal at the moment for me to start making changes to support them.

Thanks for your reply, maybe I will choose to patch the package in the node_modules to fix the problem.
