### ISSUE TITLE
How to properly extend Decimal.js-light?

### ISSUE THREAD

**Issue by shtse8** [MikeMcl/decimal.js-light#7]
I want to add some helper methods into the prototype, so I write my own class and extend Decimal.js.
It works perfectly except when calling .add() and some other operators. the super class (Decimal) is returned by default. Any ideas to properly extend Decimal?

**Comment by shwuhk** [comment]
I tried to extends Decimal.js-light, but the behavior is strange.

```
class MyDecimal extends Decimal {
    constructor(value) {
        super(value)
    }
}

let x = new MyDecimal(0)
console.log(x.constructor.name) //Tested with Chrome, it is not 'MyDecimal' but 'e'
```

Please help.

**Comment by MikeMcl** [comment]
Apologies for not replying sooner. Unfortunately, I was not able to help with this.
It is the sort of question that would have been better to ask on stackoverflow.com.
