### ISSUE TITLE
Slow toLocaleString

### ISSUE THREAD

**Issue by dcrystalj** [MikeMcl/decimal.js-light#9]
I realized that localizing decimal `toLocaleString` consumes around 3-4 ms which is huge performance problem if you need to render 100 elements which lead to 300ms scripting time and can cause rendering glitches.

Is there any workaround. Obviously this function does not feel `light` at all.

I am using version 2.5.0

**Comment by MikeMcl** [comment]
There is no `toLocaleString` here, fella.

**Comment by dcrystalj** [comment]
here is working example: 
https://codepen.io/dcrystalj/pen/eoboBM

**Comment by MikeMcl** [comment]
```js
var a = new Decimal('123.456778');
var b = (+a).toLocaleString('en-US', {minimumFractionDigits: 2, maximumFractionDigits: 4});
console.log(b);
```

In your code above, `(+a)` is equivalent to `Number(a.toString())`, so you are calling `toLocaleString` on a JavaScript number, not a Decimal. The performance of `toLocaleString` is nothing to do with this library.

How about:

```js
var a = new Decimal('123.456778');
console.log(a.toFixed(4));    // '123.4568'
```

**Comment by dcrystalj** [comment]
oh... my bad. Not sure why this is slow then if it is native. Looks like I will have to make my own localization.

`toFixed` looks fine but for specific language only. Will have to check for all other possible formats.

Thank you.
